site_name: Klein
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: 'teal'
    accent: 'deep orange'
  favicon: 'img/favicon.ico'
  feature:
    tabs: false
  logo:
    icon: 'flip'
site_url: https://jeremyong.com/Klein/
repo_url: https://github.com/jeremyong/Klein/
edit_uri: ''
repo_name: 'jeremyong/Klein'
site_description: Klein - Realtime Projective Geometric Algebra
site_author: Jeremy Ong
copyright: 'Klein Copyright &copy; 2020 Jeremy Ong'
google_analytics: ['UA-10576233-1', 'auto']

plugins: []

nav:
  - 'Home': 'index.md'
  - 'Quick Start': 'quickstart.md'
  - 'API':
      - 'Overview': 'overview.md'
      - 'Entity': 'api/kln_entity.md'
      - 'Plane': 'api/kln_plane.md'
      - 'Line': 'api/kln_line.md'
      - 'Point': 'api/kln_point.md'
      - 'Rotor': 'api/kln_rotor.md'
      - 'Translator': 'api/kln_translator.md'
      - 'Motor': 'api/kln_motor.md'
      - 'Ideal Line': 'api/kln_ideal_line.md'
      - 'Direction': 'api/kln_direction.md'
      - 'Mat4x4': 'api/kln_mat4x4.md'
      - 'Origin': 'api/kln_origin.md'
  - 'Tutorial':
      - 'Introduction': 'tutorial/intro.md'
      - 'Exterior Algebra': 'tutorial/exterior_algebra.md'
  - 'Case Studies':
      - 'Basic Skeletal Animation': 'case_studies/kinematic_chain.md'
  - 'Klein Shell': 'shell.md'
  # - 'Benchmarks': 'benchmarks.md'
  - 'Discord': 'discord.md'
  - 'Roadmap': 'roadmap.md'
  - 'References': 'references.md'

extra_css:
  - 'css/extra.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css'

extra_javascript:
  - 'js/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/gl-matrix/2.8.1/gl-matrix-min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js'
  - 'https://unpkg.com/mermaid@8.4.8/dist/mermaid.min.js'
  - 'https://cdn.jsdelivr.net/npm/ganja.js@1.0.169'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - pymdownx.arithmatex:
      generic: True
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.mark
  - pymdownx.extrarawhtml
  - toc
  - sane_lists

extra:
  social:
    - type: 'github'
      link: 'https://github.com/jeremyong'
    - type: 'twitter'
      link: 'https://twitter.com/m_ninepoints'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jeremycong'
