site_name: Klein
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: 'teal'
    accent: 'deep orange'
  favicon: 'img/favicon.ico'
  feature:
    tabs: false
  logo:
    icon: 'flip'
site_url: https://jeremyong.com/klein
repo_url: https://github.com/jeremyong/klein
repo_name: 'jeremyong/klein'
site_description: Klein - Realtime Projective Geometric Algebra
site_author: Jeremy Ong
copyright: 'Klein Copyright &copy; 2020 Jeremy Ong'
google_analytics: ['UA-10576233-1', 'auto']

plugins: []

nav:
  - 'Home': 'index.md'
  - 'Quick Start': 'quickstart.md'
  - 'API':
      - 'Entity': 'api/kln::entity.md'
      - 'Plane': 'api/kln::plane.md'
      - 'Line': 'api/kln::line.md'
      - 'Point': 'api/kln::point.md'
      - 'Rotor': 'api/kln::rotor.md'
      - 'Translator': 'api/kln::translator.md'
      - 'Motor': 'api/kln::motor.md'
      - 'Ideal Line': 'api/kln::ideal_line.md'
      - 'Direction': 'api/kln::direction.md'
      - 'Mat4x4': 'api/kln::mat4x4.md'
  - 'Tutorial': 'tutorial.md'
  - 'Klein Shell': 'shell.md'
  - 'Benchmarks': 'benchmarks.md'
  - 'Roadmap': 'roadmap.md'
  - 'References': 'references.md'

edit_uri: ''

extra_javascript:
  # - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
  - 'js/extra.js'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.extrarawhtml
  - toc
  - sane_lists

extra:
  social:
    - type: 'github'
      link: 'https://github.com/jeremyong'
    - type: 'twitter'
      link: 'https://twitter.com/m_ninepoints'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jeremycong'
